# Generated by Django 5.1.1 on 2024-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specializations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='learner_permit_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='license_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
